/** Editorial copy for each flower. Kept beside the pipeline so one script emits everything. */
export const COPY = {
  'corn-poppy': {
    alt: 'A single corn poppy in full flower, scarlet petals cupped around a black centre.',
    line: 'It waits underground for a generation, then answers the first turn of the spade.',
    note: 'Poppy seed can lie dormant in soil for decades, germinating only when the ground is broken open. That patience is why the fields of Flanders turned red after the shelling — and why the flower became the emblem of remembrance.',
    season: 'Late spring – midsummer',
    origin: 'Europe, North Africa, temperate Asia',
    meaning: 'Remembrance, sleep, consolation',
  },
  'persian-buttercup': {
    alt: 'A Persian buttercup filling the frame, coral petals layered around a dark eye.',
    line: 'A hundred and thirty petals, each one thin enough to read through.',
    note: 'The Persian buttercup packs its bloom in layer after layer of tissue-fine petals, closer to crepe paper than to a flower. It arrived in European gardens by way of Ottoman Turkey, where sultans prized it long before Europe knew it.',
    season: 'Spring',
    origin: 'Eastern Mediterranean, south-west Asia',
    meaning: 'Radiance, charm',
  },
  sunflower: {
    alt: 'A sunflower head seen straight on, gold ray petals around a densely packed brown disc.',
    line: 'The head is not one flower but two thousand, spiralling by arithmetic.',
    note: 'What reads as a single bloom is a dense colony of tiny florets, arranged in interlocking spirals that count out consecutive Fibonacci numbers — commonly 34 one way and 55 the other. Young buds follow the sun across the sky; mature heads stop, and face east for good.',
    season: 'Mid – late summer',
    origin: 'North America',
    meaning: 'Adoration, constancy',
  },
  magnolia: {
    alt: 'One magnolia bloom held clear of bare branches, cream petals flushed with mauve.',
    line: 'Older than bees, so it was built for beetles instead.',
    note: 'Magnolias appeared before bees existed, and evolved tough, thick-walled flowers that could survive the chewing of beetles — still their principal pollinators. This saucer magnolia is a hybrid, raised outside Paris in the 1820s by Étienne Soulange-Bodin, a cavalry officer turned horticulturist.',
    season: 'Early spring, before the leaves',
    origin: 'Garden hybrid; parent species from China',
    meaning: 'Dignity, perseverance',
  },
  'cherry-blossom': {
    alt: 'A cluster of double cherry blossoms, pale pink and crowded, against dark foliage.',
    line: 'Its whole argument is that it will be gone in a week.',
    note: 'Sakura holds Japan\'s attention for a fortnight at most, and the brevity is the point — the blossom is the standing image of mono no aware, the gentle ache at things passing. Forecasters track the bloom front north up the archipelago each spring.',
    season: 'Spring, one to two weeks',
    origin: 'Japan, Korea, China',
    meaning: 'Transience, renewal',
  },
  'king-protea': {
    alt: 'A king protea, pointed pink bracts opening around a dense white crown.',
    line: 'Named for a god who could become anything he liked.',
    note: 'Linnaeus named the genus after Proteus, the shape-shifter of Greek myth, for the sheer variety of forms it takes. The king protea carries the largest head in the genus — up to 30 cm across — and survives fire by resprouting from a thick underground rootstock.',
    season: 'Autumn – spring',
    origin: 'Cape fynbos, South Africa',
    meaning: 'Courage, transformation',
  },
  lavender: {
    alt: 'Backlit lavender spikes, violet flowers ranged along slender grey-green stems.',
    line: 'The name is a verb: to wash.',
    note: 'Lavandula traces to the Latin lavare, from the Roman habit of scenting baths and laundry with it. The colour is largely in the bracts rather than the small flowers themselves, which is why a field holds its purple long after the bloom is over.',
    season: 'Mid – late summer',
    origin: 'Mediterranean uplands',
    meaning: 'Calm, devotion',
  },
  'bearded-iris': {
    alt: 'A bearded iris close up, deep violet falls marked with a golden beard.',
    line: 'Named for the rainbow, and it takes the whole spectrum personally.',
    note: 'Iris was the Greek goddess who carried messages along the rainbow, and the genus has spent the time since earning the name. The fuzzy strip on each falling petal — the beard — is a landing strip, steering bees toward the pollen.',
    season: 'Late spring',
    origin: 'Southern and central Europe',
    meaning: 'Wisdom, hope, faith',
  },
  cornflower: {
    alt: 'A cornflower in vivid blue, its fringed florets standing against ripe golden wheat.',
    line: 'A weed so beautiful that saving it took an act of policy.',
    note: 'Cornflower once ran riot through European grain fields; modern herbicides very nearly finished it, and it is now scarce in much of its old range. Estonia made it a national symbol, and conservation sowings have brought the blue back to field margins.',
    season: 'Summer',
    origin: 'Europe, naturalised widely',
    meaning: 'Hope, delicacy',
  },
  'water-lily': {
    alt: 'A white water lily open on still water, yellow stamens at the centre, jade pads around it.',
    line: 'Roots in the mud, and it never mentions it.',
    note: 'Nymphaea alba anchors in the silt of still water and pushes its bloom clear of the surface, opening in the morning and closing again by afternoon. The flower has carried the same meaning across unrelated cultures for millennia: something clean rising out of something that is not.',
    season: 'Summer',
    origin: 'Europe, North Africa, the Middle East',
    meaning: 'Purity, rebirth',
  },
};
